import fs from 'fs';
import path from 'path';
import { Adapter, StackConfig, InstalledComponent } from '../types';
import { ensureDir, logSuccess, logError } from '../utils';

const BARE_KEY_RE = /^[A-Za-z0-9_-]+$/;

function quoteTomlKey(id: string): string {
  return BARE_KEY_RE.test(id) ? id : JSON.stringify(id);
}

function escapeTomlString(s: string): string {
  return JSON.stringify(s);
}

function formatTomlValue(v: unknown): string {
  if (typeof v === 'string') return escapeTomlString(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) return '[' + v.map(item => escapeTomlString(String(item))).join(', ') + ']';
  return escapeTomlString(String(v));
}

export class CodexAdapter implements Adapter {
  async exportConfig(
    stack: StackConfig,
    installed: { skills: InstalledComponent[]; agents: InstalledComponent[]; mcps: InstalledComponent[] },
    outputDir: string
  ): Promise<void> {
    try {
      await ensureDir(outputDir);

      const lines: string[] = [
        '# Generated by aipm — Codex MCP servers and plugins from stack.yaml',
        '# Merge into ~/.codex/config.toml or use as reference',
        '',
      ];

      const targetConfig = stack.targets['codex'];
      if (!targetConfig) {
        const outputPath = path.join(outputDir, '.codex', 'stack-export.toml');
        await ensureDir(path.dirname(outputPath));
        await fs.promises.writeFile(outputPath, lines.join('\n'), 'utf8');
        return;
      }

      // MCP servers
      if (targetConfig.mcps && targetConfig.mcps.length > 0) {
        for (const mcpId of targetConfig.mcps) {
          const mcpDef = stack.mcps?.find(m => m.id === mcpId);
          if (!mcpDef) {
            logError(`MCP ${mcpId} not found in stack configuration, skipping`);
            continue;
          }

          lines.push(`[mcp_servers.${quoteTomlKey(mcpId)}]`);
          lines.push('enabled = true');

          if (mcpDef.url) {
            lines.push(`url = ${escapeTomlString(mcpDef.url)}`);
          }
          if (mcpDef.command) {
            lines.push(`command = ${escapeTomlString(mcpDef.command)}`);
          }
          if (mcpDef.args && mcpDef.args.length > 0) {
            lines.push(`args = ${formatTomlValue(mcpDef.args)}`);
          }
          if (mcpDef.transport) {
            lines.push(`type = ${escapeTomlString(mcpDef.transport)}`);
          }

          if (mcpDef.env && Object.keys(mcpDef.env).length > 0) {
            lines.push(`[mcp_servers.${quoteTomlKey(mcpId)}.env]`);
            for (const [key, val] of Object.entries(mcpDef.env)) {
              lines.push(`${key} = ${escapeTomlString(val)}`);
            }
          }

          lines.push('');
        }
      }

      // Agents → plugins
      if (targetConfig.agents && targetConfig.agents.length > 0) {
        for (const agentId of targetConfig.agents) {
          const installedAgent = installed.agents.find(a => a.id === agentId);
          const inlineAgent = (stack.agents || []).find(a => a.id === agentId && !a.source);

          if (installedAgent || inlineAgent) {
            lines.push(`[plugins.${quoteTomlKey(agentId)}]`);
            lines.push('enabled = true');
            lines.push('');
          } else {
            logError(`Agent ${agentId} not installed, skipping`);
          }
        }
      }

      // Skills — Codex has no direct skill equivalent; note as comments
      if (targetConfig.skills && targetConfig.skills.length > 0) {
        lines.push('# Skills (no direct Codex equivalent — review and map to plugins if needed):');
        for (const skillId of targetConfig.skills) {
          const installedSkill = installed.skills.find(s => s.id === skillId);
          if (installedSkill) {
            lines.push(`#   ${skillId} @ ${installedSkill.version} — ${installedSkill.path}`);
          } else {
            lines.push(`#   ${skillId} — not installed`);
          }
        }
        lines.push('');
      }

      const outputPath = path.join(outputDir, '.codex', 'stack-export.toml');
      await ensureDir(path.dirname(outputPath));
      await fs.promises.writeFile(outputPath, lines.join('\n'), 'utf8');

      logSuccess(`Exported Codex configuration to ${outputPath}`);
    } catch (error) {
      logError(`Failed to export Codex configuration: ${(error as Error).message}`);
      throw error;
    }
  }
}
