import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { Adapter, StackConfig, InstalledComponent } from '../types';
import { ensureDir, logSuccess, logError } from '../utils';

function sanitizePathSegment(id: string): string {
  return id.replace(/\.\./g, '').replace(/[/\\]/g, '_');
}

export class HermesAdapter implements Adapter {
  async exportConfig(
    stack: StackConfig,
    installed: { skills: InstalledComponent[]; agents: InstalledComponent[]; mcps: InstalledComponent[] },
    outputDir: string
  ): Promise<void> {
    try {
      await ensureDir(outputDir);

      const config: any = {
        mcp_servers: {},
        agents: {},
      };

      const targetConfig = stack.targets['hermes'];
      if (!targetConfig) {
        const outputPath = path.join(outputDir, '.hermes', 'stack-export.yaml');
        await ensureDir(path.dirname(outputPath));
        await fs.promises.writeFile(outputPath, yaml.dump(config, { lineWidth: 120, noRefs: true }), 'utf8');
        return;
      }

      // MCP servers
      if (targetConfig.mcps) {
        for (const mcpId of targetConfig.mcps) {
          const mcpDef = stack.mcps?.find(m => m.id === mcpId);
          if (!mcpDef) {
            logError(`MCP ${mcpId} not found in stack configuration, skipping`);
            continue;
          }

          const server: any = { enabled: true };

          if (mcpDef.url) {
            server.url = mcpDef.url;
          }
          if (mcpDef.command) {
            server.command = mcpDef.command;
          }
          if (mcpDef.args && mcpDef.args.length > 0) {
            server.args = mcpDef.args;
          }
          if (mcpDef.env && Object.keys(mcpDef.env).length > 0) {
            server.env = mcpDef.env;
          }
          if (mcpDef.transport) {
            server.transport = mcpDef.transport;
          }

          config.mcp_servers[mcpId] = server;
        }
      }

      // Agents
      if (targetConfig.agents) {
        for (const agentId of targetConfig.agents) {
          const installedAgent = installed.agents.find(a => a.id === agentId);
          const inlineAgent = (stack.agents || []).find(a => a.id === agentId && !a.source);

          if (installedAgent) {
            config.agents[agentId] = {
              path: installedAgent.path,
              version: installedAgent.version,
            };
          } else if (inlineAgent) {
            const agentConfig: any = {};
            if (inlineAgent.model) agentConfig.model = inlineAgent.model;
            if (inlineAgent.system) agentConfig.system = inlineAgent.system;
            if (inlineAgent.skills && inlineAgent.skills.length > 0) {
              agentConfig.skills = inlineAgent.skills;
            }
            config.agents[agentId] = agentConfig;
          } else {
            logError(`Agent ${agentId} not installed, skipping`);
          }
        }
      }

      // Write YAML config
      const outputPath = path.join(outputDir, '.hermes', 'stack-export.yaml');
      await ensureDir(path.dirname(outputPath));
      await fs.promises.writeFile(
        outputPath,
        '# Generated by aipm — Hermes MCP servers and agents from stack.yaml\n' +
        '# Merge into ~/.hermes/config.yaml or use as reference\n\n' +
        yaml.dump(config, { lineWidth: 120, noRefs: true, sortKeys: false }),
        'utf8'
      );

      // Write skills as markdown files
      if (targetConfig.skills && targetConfig.skills.length > 0) {
        for (const skillId of targetConfig.skills) {
          const installedSkill = installed.skills.find(s => s.id === skillId);
          if (!installedSkill) {
            logError(`Skill ${skillId} not installed, skipping`);
            continue;
          }

          const skillDir = path.join(outputDir, '.hermes', 'skills', sanitizePathSegment(skillId));
          await ensureDir(skillDir);

          // Copy the actual skill content from the installed entry file
          const skillDef = (stack.skills || []).find(s => s.id === skillId);
          const entryFile = skillDef?.entry || './SKILL.md';
          const sourcePath = path.join(installedSkill.path, entryFile);

          let skillContent: string;
          if (fs.existsSync(sourcePath)) {
            skillContent = await fs.promises.readFile(sourcePath, 'utf8');
          } else {
            skillContent = [
              `# ${skillId}`,
              '',
              `**Version:** ${installedSkill.version}`,
              `**Source:** ${installedSkill.source}`,
              '',
              'Installed via aipm. Original entry file not found.',
            ].join('\n') + '\n';
          }

          await fs.promises.writeFile(path.join(skillDir, 'SKILL.md'), skillContent, 'utf8');
        }
      }

      logSuccess(`Exported Hermes configuration to ${outputPath}`);
    } catch (error) {
      logError(`Failed to export Hermes configuration: ${(error as Error).message}`);
      throw error;
    }
  }
}
